title: Biomedical literature annotations
author: "https://github.com/neurodatascience/labelbuddy-annotations/graphs/contributors"

parse:
  myst_substitutions:
    labelbuddy_home: "[labelbuddy](https://jeromedockes.github.io/labelbuddy/)"
    labelbuddy_doc: "[labelbuddy documentation](https://jeromedockes.github.io/labelbuddy/labelbuddy/current/documentation/)"
    lb: "**labelbuddy**"
    pmc_home: "[PubMedCentral](https://www.ncbi.nlm.nih.gov/pmc/)"
    pubget_home: "[pubget](https://neuroquery.github.io/pubget/)"
    git: "**Git**"
    pg: "**pubget**"
    repo_blob_url: "https://github.com/neurodatascience/labelbuddy-annotations/blob/main/"
    repo_tree_url: "https://github.com/neurodatascience/labelbuddy-annotations/tree/main/"
    repo_issues_url: "https://github.com/neurodatascience/labelbuddy-annotations/issues"
    repo_url: "https://github.com/neurodatascience/labelbuddy-annotations/"

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: "https://github.com/neurodatascience/labelbuddy-annotations"
  path_to_book: analysis/book
  branch: main

html:
  use_issues_button: false
  use_repository_button: true

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py
